### ISSUE TITLE
Error in utils.py when evaluating

### ISSUE THREAD

**Issue by stingerpk** [NervanaSystems/deepspeech#50]
Hello, I am using evaluating using the following command:

`python evaluate.py --manifest val:/path/to/manifest.csv --model_file /path/to/librispeech_16_epochs.prm --use_wer --inference_file /path/to/results.pkl`

I get the following error:

```ssh
Traceback (most recent call last):
  File "evaluate.py", line 103, in <module>
    use_wer=args.use_wer)
  File "/home/ubuntu/nervana/deepspeech/speech/utils.py", line 75, in get_wer
    progress_string = get_progress_string(be.bsz, batchcount, nbatches)
  File "/home/ubuntu/nervana/deepspeech/speech/utils.py", line 23, in get_progress_string
    bar_width = int(float(bcount) / nbatches * max_bar_width)
ZeroDivisionError: float division by zero
```

I am using current master versions of aeon, neon and deepspeech.

**Comment by tyler-nervana** [comment]
Could you show a few lines of your manifest file? That error indicates that `nbatches` is 0, but that implies that your dataset has 0 items in it.
