### ISSUE TITLE
Evaluation issue with new data

### ISSUE THREAD

**Issue by saikishor** [NervanaSystems/deepspeech#59]
When I am trying to evaluate with the new data. I find it too complex and finally ended up with error. Ay idea?

2017-10-12 21:51:54,705 - neon.backends - WARNING - deterministic_update and deterministic args are deprecated in favor of specifying random seed
OpenCV Error: One of arguments' values is out of range (Bad new number of rows) in reshape, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp, line 805
OpenCV Error: One of arguments' values is out of range (Bad new number of rows) in reshape, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp, line 805
OpenCV Error: One of arguments' values is out of range (Bad new number of rows) in reshape, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp, line 805
OpenCV Error: One of arguments' values is out of range (Bad new number of rows) in reshape, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp, line 805
[ERR ] 2017-10-12T19:51:55z api.cpp 327	Unable to create internal loader object
Traceback (most recent call last):
  File "evaluate.py", line 66, in <module>
    max_utt_len, backend_obj=be)
  File "/home/saikishor/Deepspeech/deepspeech/speech/data/dataloader.py", line 58, in make_loader
    return wrap_dataloader(AeonDataLoader(aeon_config))
  File "/home/saikishor/Deepspeech/neon/neon/data/aeon_shim.py", line 32, in AeonDataLoader
    return DataLoaderAdapter(AeonLoader(config))
RuntimeError: Unable to create internal loader object: /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp:805: error: (-211) Bad new number of rows in function reshape

config is: {"batch_size":32,"block_size":32,"etl":[{"emit_length":true,"feature_type":"mfsc","frame_length":"25 milliseconds","frame_stride":"10 milliseconds","max_duration":"30 seconds","num_filters":13,"sample_freq_hz":16000,"type":"audio"},{"alphabet":"_'ABCDEFGHIJKLMNOPQRSTUVWXYZ ","emit_length":true,"max_length":1300,"type":"char_map"}],"manifest_filename":"/home/saikishor/Deepspeech/librispeech/dev-clean_new/david-manifest.csv","manifest_root":"/home/saikishor/Deepspeech/librispeech/dev-clean_new"}

**Comment by tyler-nervana** [comment]
Could you post an example audio file from your new dataset?
