### ISSUE TITLE
AssertionError while evaluating model Zoo pre-trained librispeech model

### ISSUE THREAD

**Issue by shaofushih** [NervanaSystems/deepspeech#63]
Environment: 
python 2.7, CUDA 8.0

Command Executed:
python evaluate.py --manifest val:dev-clean.csv --model_file librispeech_16_epochs.prm
2017-11-13 13:38:52,729 - neon.backends - WARNING - deterministic_update and deterministic args are deprecated in favor of specifying random seed
Traceback (most recent call last):
  File "evaluate.py", line 69, in <module>
    model = Model(args.model_file)
  File "/home/root/neon/neon/models/model.py", line 72, in __init__
    self.load_params(layers, load_states=(not weights_only))
  File "/home/root/neon/neon/models/model.py", line 418, in load_params
    self.deserialize(load_obj(param_path), load_states=load_states)
  File "/home/root/neon/neon/models/model.py", line 479, in deserialize
    self.layers.load_weights(model_dict['model'], load_states)
  File "/home/root/neon/neon/layers/container.py", line 200, in load_weights
    assert len(pdict['config']['layers']) == len(self.layers)
AssertionError

However when I am testing my own trained model (randomly trained). The script seems to be working just fine. Not sure why this is occurring, could this be due to cross compatibility again?

**Comment by wei-v-wang** [comment]
Hello this is a known issue and has yet to upload the new format of librispeech_16_epochs.prm.
